### ISSUE TITLE
#1 Общее задание. Выбрать модули.

### ISSUE THREAD

**Issue by TOL00773** [TOL00773/Audioplayer-for-android#1]
1. Договориться о названии приложения и необходимой версии ПО.
2. Разработать макет будущего приложения.
3. Создать каркас приложения.
4. Добавить кнопку "Play", которая начинает воспроизведение файла mp3
5. Добавить кнопку "Pause", которая приостанавливает воспроизведение файла mp3
6. Добавить кнопrу "Stop", которая останавливает воспроизведение файла mp3
7. Добавить кнопки "<<" и  ">>", которые перематывают файл назад и вперед соответственно.
8. Добавить кнопки "|<"и  ">|",  которые переключают воспроизведение на предыдущий и следующий файл.
9. Написать документацию к данному проекту.

**Comment by Ptize** [comment]
Готов сделать 2,7,8 пункты и описать их в 9

**Comment by TOL00773** [comment]
Хорошо, тогда я возьму 3, 4, 5, 6 модули и описать их в 9. 
1 пункт общий
