### ISSUE TITLE
Добавить кнопку отключения звука и кнопку повтора файла

### ISSUE THREAD

**Issue by TOL00773** [TOL00773/Audioplayer-for-android#13]

**Comment by Ptize** [comment]
Принято

**Comment by Ptize** [comment]
Кнопки добавлены и всё сделано, кроме одного. Не найдено место перехода от одного трека к другому. В это место надо вставить 2 строчки. Номер строки, в которую сейчас вставлены данные строки закомментирован в первой строке файла MainActivity

**Comment by TOL00773** [comment]
Ошибка исправленна
