### ISSUE TITLE
#2 Договориться о названии приложения и необходимой версии ПО.

### ISSUE THREAD

**Issue by TOL00773** [TOL00773/Audioplayer-for-android#2]
Предлагаем свои варианты.

**Comment by TOL00773** [comment]
Предлагаю название приложения: AudioPlayer
Необходимая версия ПО: android 4.2.2

**Comment by Ptize** [comment]
Предлагаю: your special audio player Prize;
Необходимая минимальная версия ПО 4.0.3

**Comment by TOL00773** [comment]
Согласен с минимальной версией. Насчет названия думаю нужно выбрать что-нибудь попроще

**Comment by Ptize** [comment]
Основное название: Приз(Prize), остальное приписка

**Comment by TOL00773** [comment]
Я, как руководитель проекта, принял решение:
1. Название приложения: AudioPlayer
2. Минимальная версия ПО: Android 4.0.3
