### ISSUE TITLE
#3 Разработать макет будущего приложения.

### ISSUE THREAD

**Issue by TOL00773** [TOL00773/Audioplayer-for-android#3]
Разработать схематично макет будущего приложения

**Comment by Ptize** [comment]
Принял. Начинаю работу.

**Comment by Ptize** [comment]
Итак, предлагаю сначала реализовать данный макет аудиоплеера: ![image](https://user-images.githubusercontent.com/29841352/27832878-12a22472-60d9-11e7-8f89-f28c0864f5ad.png)

**Comment by Ptize** [comment]
При последующих обновлениях и дополнениях в данный макет можно внести некоторые поправки, которые приведут его к одному из следующих видов: 
![image](https://user-images.githubusercontent.com/29841352/27832982-759492d6-60d9-11e7-8614-a56072389045.png)
![image](https://user-images.githubusercontent.com/29841352/27832994-7deedc02-60d9-11e7-9b48-f79be7130a9f.png)
![image](https://user-images.githubusercontent.com/29841352/27832999-83b680ae-60d9-11e7-8ee0-2c199b55be41.png)

**Comment by Ptize** [comment]
Предлагаю при следующих обновлениях и дополнениях привести приложение к одному из следующих видов:
![image](https://user-images.githubusercontent.com/29841352/27833139-2399970a-60da-11e7-8c8d-d29a71091535.png)
![image](https://user-images.githubusercontent.com/29841352/27833156-31a4cf40-60da-11e7-8cb4-5868a3fc6d88.png)
![image](https://user-images.githubusercontent.com/29841352/27833163-396e0d90-60da-11e7-9444-e012f4395f72.png)

**Comment by TOL00773** [comment]
Идею понял. Макет принят.
