### ISSUE TITLE
#5 Добавить кнопку "Play"

### ISSUE THREAD

**Issue by TOL00773** [TOL00773/Audioplayer-for-android#5]
Добавить кнопку "Play", которая начинает воспроизведение файла mp3

**Comment by TOL00773** [comment]
По просьбе Ptize загрузил проект полностью. 
5, 6, 7 модули готовы. Требуется проверка.

**Comment by Ptize** [comment]
Проверил код. С ним всё в порядке. Для определения работоспособности приложения требуется тестирование на целевом устройстве

**Comment by Ptize** [comment]
Закрывай 5,6,7 задачи и открывай новую "тестирование"
