### ISSUE TITLE
#8 Добавить кнопки "<<" и ">>"

### ISSUE THREAD

**Issue by TOL00773** [TOL00773/Audioplayer-for-android#8]
Добавить кнопки "<<" и ">>", которые перематывают файл назад и вперед соответственно.

**Comment by Ptize** [comment]
Перемотка файла реализована в seekbar, кнопки не требуются, предлагаю изменить макет и добавить "повтор" и режим "без звука"

**Comment by TOL00773** [comment]
Согласен
